### ISSUE TITLE
Colaboratory上train.sh报错

### ISSUE THREAD

**Issue by RancherJie** [7eu7d7/pixiv_AI_crawler#18]
`/Data/MyDrive/pixiv_AI_crawler
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/Data/MyDrive/pixiv_AI_crawler/main.py", line 488, in <module>
    main(args)
  File "/Data/MyDrive/pixiv_AI_crawler/main.py", line 210, in main
    utils.init_distributed_mode(args)
  File "/Data/MyDrive/pixiv_AI_crawler/utils.py", line 337, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Traceback (most recent call last):
  File "/Data/MyDrive/pixiv_AI_crawler/main.py", line 488, in <module>
    main(args)
  File "/Data/MyDrive/pixiv_AI_crawler/main.py", line 210, in main
    utils.init_distributed_mode(args)
  File "/Data/MyDrive/pixiv_AI_crawler/utils.py", line 337, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 261, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
Killing subprocess 2546
Killing subprocess 2547
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3.9', '-u', 'main.py', '--local_rank=1', '--model', 'convnext_tiny', '--drop_path', '0.5', '--input_size', '384', '--batch_size', '48', '--lr', '2e-4', '--update_freq', '2', '--nb_classes', '3', '--warmup_epochs', '0', '--epochs', '60', '--weight_decay', '1e-8', '--head_init_scale', '0.001', '--cutmix', '0', '--mixup', '0', '--save_ckpt_num', '100', '--dist_eval', 'False', '--color_jitter', '0.2', '--finetune', 'ckpt/convnext_tiny_22k_1k_384.pth', '--data_path', '/dataset/dzy/anime_ds', '--eval_data_path', '/dataset/dzy/anime_ds', '--imset', './imset/', '--data_set', 'json', '--output_dir', 'output/tiny6']' returned non-zero exit status 1.`

**Comment by Q78KG** [comment]
同求
