### ISSUE TITLE
找不到模块

### ISSUE THREAD

**Issue by Q78KG** [7eu7d7/pixiv_AI_crawler#2]
Traceback (most recent call last):
  File "D:\Github\pixiv_AI_crawler\AIcrawler.py", line 4, in <module>
    from torchvision import transforms, models
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\torchvision\__init__.py", line 5, in <module>
    from torchvision import datasets
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\torchvision\datasets\_optical_flow.py", line 10, in <module>
    from PIL import Image
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by 7eu7d7** [comment]
pip uninstall Pillow
pip install Pillow
卸载重装Pillow试试，python要<=3.9版本的

**Comment by Q78KG** [comment]
变成这样了
Traceback (most recent call last):
  File "D:\Github\pixiv_AI_crawler\AIcrawler.py", line 6, in <module>
    from timm.models import create_model
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\models\__init__.py", line 1, in <module>
    from .cspnet import *
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\models\cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\models\helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\models\layers\__init__.py", line 7, in <module>
    from .cond_conv2d import CondConv2d, get_condconv_initializer
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\models\layers\cond_conv2d.py", line 16, in <module>
    from .helpers import to_2tuple
  File "C:\Users\Q78KG\miniconda3\lib\site-packages\timm\models\layers\helpers.py", line 6, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (C:\Users\Q78KG\miniconda3\lib\site-packages\torch\_six.py)

**Comment by Q78KG** [comment]
安装全程没有任何报错，py版本也没错

**Comment by 7eu7d7** [comment]
pytorch需要1.8.x版本的，你是不是装高版本了

**Comment by Q78KG** [comment]
我lts装不上，就直接装了普通的
因为我是镜像源

**Comment by 7eu7d7** [comment]
torch=1.8.2或1.8.1  torchvision=0.9.2

**Comment by Q78KG** [comment]
我逝逝
